CREATE TABLE [dbo].[Books]
(
	[Id] INT IDENTITY (1, 1) NOT NULL, CONSTRAINT PK_BookId PRIMARY KEY CLUSTERED (Id),
    [Title] VARCHAR(100) NOT NULL,
    [Author] VARCHAR(100) NOT NULL, 
	[PublishedOn] DATETIME2 NOT NULL,
	[ISBN] VARCHAR(50) NOT NULL, 
	[Description] VARCHAR(500) NULL,
	[IsActive] BIT NOT NULL DEFAULT 1,
	[Price] DECIMAL(18, 2) NOT NULL, 
    [Pages] NUMERIC(6) NOT NULL,
	[PictureUrl] VARCHAR(100) NULL, 
)